/**
 * Cue Foundations · shared preview map.
 * ─────────────────────────────────────────────────────
 * AUTO-GENERATED by scripts/migrate-from-cue.mjs. Hand-crafted
 * entries at the top are pinned; auto-generated ones follow.
 * Regenerated on every `npm run sync-kit` — do not edit by hand.
 * ─────────────────────────────────────────────────────
 */

import { MagneticButtonPreview } from "@/components/previews/foundations/button-magnetic"
import { TiltCardPreview } from "@/components/previews/foundations/tilt-card"
import { ThemeTogglePreview } from "@/components/previews/foundations/theme-toggle"
import { TabsPillPreview } from "@/components/previews/foundations/tabs-pill"
import { LiveWaveformAudioRecorderPreview } from "@/components/previews/foundations/live-waveform-audio-recorder"
import { ExpandableShareCardPreview } from "@/components/previews/foundations/expandable-share-card"
import { CellToCardCalendarExpansionPreview } from "@/components/previews/foundations/cell-to-card-calendar-expansion"
import { DotGraphCardPreview } from "@/components/previews/foundations/dot-graph-card"
import { GlossySliderCallButtonPreview } from "@/components/previews/foundations/glossy-slider-call-button"
import { StackerStyleBentoGridPreview } from "@/components/previews/foundations/stacker-style-bento-grid"
import { PhantomInfiniteGalleryPreview } from "@/components/previews/foundations/phantom-infinite-gallery"
import { SplitPanelImageSyncedFaqFeaturesPreview } from "@/components/previews/foundations/split-panel-image-synced-faq-features"
import { CollapsingCardsAccordionPreview } from "@/components/previews/foundations/collapsing-cards-accordion"
import { MinimalAiDevWorkspacePreview } from "@/components/previews/foundations/minimal-ai-dev-workspace"
import { DynamicIslandFeedbackNotchPreview } from "@/components/previews/foundations/dynamic-island-feedback-notch"
import { ExpandableBookSearchPalettePreview } from "@/components/previews/foundations/expandable-book-search-palette"
import { _3dBookCarouselReadingModePreview } from "@/components/previews/foundations/3d-book-carousel-reading-mode"
import { DynamicNotchActivityIndicatorPreview } from "@/components/previews/foundations/dynamic-notch-activity-indicator"
import { FlexGrowBenefitsRevealPreview } from "@/components/previews/foundations/flex-grow-benefits-reveal"
import { AddProductWizardModalPreview } from "@/components/previews/foundations/add-product-wizard-modal"
import { ChainedSpringArcCarouselPreview } from "@/components/previews/foundations/chained-spring-arc-carousel"
import { FisheyeChromaticCardGridPreview } from "@/components/previews/foundations/fisheye-chromatic-card-grid"
import { SyntXHardwareMediaPlayerPreview } from "@/components/previews/foundations/synt-x-hardware-media-player"

export const SAFE_LIVE_SLUGS = new Set([
  "button-magnetic",
  "tilt-card",
  "theme-toggle",
  "tabs-pill",
  "live-waveform-audio-recorder",
  "expandable-share-card",
  "cell-to-card-calendar-expansion",
  "dot-graph-card",
  "glossy-slider-call-button",
  "stacker-style-bento-grid",
  "phantom-infinite-gallery",
  "split-panel-image-synced-faq-features",
  "collapsing-cards-accordion",
  "minimal-ai-dev-workspace",
  "dynamic-island-feedback-notch",
  "expandable-book-search-palette",
  "3d-book-carousel-reading-mode",
  "dynamic-notch-activity-indicator",
  "flex-grow-benefits-reveal",
  "add-product-wizard-modal",
  "chained-spring-arc-carousel",
  "fisheye-chromatic-card-grid",
  "synt-x-hardware-media-player",
])

export const PREVIEW_MAP: Record<string, () => React.JSX.Element> = {
  "button-magnetic": MagneticButtonPreview,
  "tilt-card": TiltCardPreview,
  "theme-toggle": ThemeTogglePreview,
  "tabs-pill": TabsPillPreview,
  "live-waveform-audio-recorder": LiveWaveformAudioRecorderPreview,
  "expandable-share-card": ExpandableShareCardPreview,
  "cell-to-card-calendar-expansion": CellToCardCalendarExpansionPreview,
  "dot-graph-card": DotGraphCardPreview,
  "glossy-slider-call-button": GlossySliderCallButtonPreview,
  "stacker-style-bento-grid": StackerStyleBentoGridPreview,
  "phantom-infinite-gallery": PhantomInfiniteGalleryPreview,
  "split-panel-image-synced-faq-features": SplitPanelImageSyncedFaqFeaturesPreview,
  "collapsing-cards-accordion": CollapsingCardsAccordionPreview,
  "minimal-ai-dev-workspace": MinimalAiDevWorkspacePreview,
  "dynamic-island-feedback-notch": DynamicIslandFeedbackNotchPreview,
  "expandable-book-search-palette": ExpandableBookSearchPalettePreview,
  "3d-book-carousel-reading-mode": _3dBookCarouselReadingModePreview,
  "dynamic-notch-activity-indicator": DynamicNotchActivityIndicatorPreview,
  "flex-grow-benefits-reveal": FlexGrowBenefitsRevealPreview,
  "add-product-wizard-modal": AddProductWizardModalPreview,
  "chained-spring-arc-carousel": ChainedSpringArcCarouselPreview,
  "fisheye-chromatic-card-grid": FisheyeChromaticCardGridPreview,
  "synt-x-hardware-media-player": SyntXHardwareMediaPlayerPreview,
}
